### ISSUE TITLE
Unclear: manifest.compatibleVersion property

### ISSUE THREAD

**Issue by turbobabr** [BohemianCoding/developer.sketchapp.com#1]
> A string specifying the version of Sketch in which the author has tested the Plugin, for example 3, 3.1, 3.2.2.

It's unclear how Sketch handles this property and it's not explained in the docs. Here are questions developer might come up with regarding it:
- Is it required?
- Does it affect plugins listing on the sketch site somehow?
- What if `compatibleVersion` property is set to `3.3.1` and plugin is installed in `3.4` environment? Would it be ignored by Sketch or marked as incompatible or obsolete?
- How `x` is handled in `3.4.x`? Is it handled at all? Do we have to provide a full version or `major.minor` is enough?

It would be nice to have a short explanation how it's handled.

**Comment by bomberstudios** [comment]
I think we're currently not doing anything with it, but the idea is to do some checks in the future, so we can show a warning if a plugin hasn't been tested with a particular Sketch version.

I'll check with Johnnie and update the docs accordingly, thanks for asking! : )

**Comment by randomsequence** [comment]
Sketch doesn't currently do anything with this. The intention was to have a warning triangle or something in the UI, which would prompt the user to look for an updated version. I think it fell by the wayside when we realised we couldn't auto-update plugins inside the MAS.

**Comment by randomsequence** [comment]
> Is it required?

No

> Does it affect plugins listing on the sketch site somehow?

Could do!

> What if compatibleVersion property is set to 3.3.1 and plugin is installed in 3.4 environment? Would it be ignored by Sketch or marked as incompatible or obsolete?

Ignored currently.

> How x is handled in 3.4.x? Is it handled at all? Do we have to provide a full version or major.minor is enough?

Internally it uses the `BCCompareVersions` function, which splits the string by `.`, then compares the integer value of each component. So `x` isn't a valid value, but won't break. It will be interpreted the same as `0`.
