### ISSUE TITLE
Remove a page

### ISSUE THREAD

**Issue by oltodo** [BohemianCoding/developer.sketchapp.com#100]
Hi, I tried without success to remove a page using the API.

__Example :__

_Suppose I have two pages_

```js
var pages = context.document.pages;
pages[1].removeFromParent();
```

There is no error but the page is still here.

Did I make mistakes?
Thanks.

**Comment by bomberstudios** [comment]
Try this:

```
var data = context.document.documentData()
data.removePageAtIndex(1)
var pages = context.document.pages()
data.setCurrentPage(pages.firstObject())
```

**Comment by oltodo** [comment]
Indeed it works ! Thanks @bomberstudios.
