### ISSUE TITLE
Please make the text able to transform within a symbol please!!

### ISSUE THREAD

**Issue by Lauradance** [BohemianCoding/developer.sketchapp.com#101]
Hi Sketch team, 

I am just an UX/UI designer, I found this is really a critical issue that every designer facing when using Sketch, when i making a layout for desktop and responsive for mobile, e.g. the headline should be smaller in mobile version, while i want to make the headline as a symbol so i can edit once for revision later, but once i turn the headline into a symbol, the text inside will not resize accordingly when i resize the symbol. It is really frustrating and I found many many designer need this function. Would you guys consider to fix it? 
Another suggestion for this issue, the overrides feature should able to let user select other pre-set text-style, so that 2 same symbol can show different text-style.
Many many thanks!! 

p.s. I'm already fall in love to use Sketch once i started few months ago, it is a perfect tools for UX/UI designer and hope it will improve more details from designer point of view. 
Cheers!

**Comment by bomberstudios** [comment]
Hi there,

this is a repository to discuss development of Plugins and Extensions for Sketch. If you need support for Sketch itself, please get in touch with us at https://sketchapp.com/support/contact/

Thanks! : )
