### ISSUE TITLE
Is there an API for Sketch to unlock the size of MSBitmapLayer?

### ISSUE THREAD

**Issue by 7thheaven** [BohemianCoding/developer.sketchapp.com#108]
The unlock size button in Sketh App

![image](https://i.stack.imgur.com/08PZo.jpg)

I can click this button to unlock the size of a layer in Sketch App. And then I can change the width/height ratio of the image. But I want my Sketch plugin to do this job instead of using my hand to click the button. Is there an API for Sketch to unlock the size of MSBitmapLayer?

I've tried "[layer setIsLocked:false]", but it's not about the size lock.

Thank you very much.

**Comment by ajilderda** [comment]
Isn't `setConstrainProportions` what you want?
See in use here: https://github.com/ErikFontanel/sketch-toggle-constrain-proportions/blob/master/Toggle%20Constrain%20Proportions.sketchplugin/Contents/Sketch/script.js

**Comment by 7thheaven** [comment]
@ajilderda Yes, it works. Thank you!
