### ISSUE TITLE
How are artboard IDs generated?

### ISSUE THREAD

**Issue by calaca88** [BohemianCoding/developer.sketchapp.com#110]
By using `artboard.objectID()`, I can output unique IDs for artboards in this format:
`4E67C28C-A7B8-460B-9C34-B3EA92AB557A`

However, I've noticed that the 1st character in the 3rd set of alpha-numeric characters is always the number `4`. I would like to know more about how these IDs are generated because I would like to use them as unique page identifiers for quick and easy reference, but an ID of this size is far too long for practical purposes. 

My solution is to generate "friendlier" IDs by only using a portion of the ID (say 4-5 consecutive characters) for each artboard and then to check for duplicates, but I want to make sure that the section I'm extracting from is definitely a random set of characters, unlike the 3rd set.

**Comment by bomberstudios** [comment]
That '4' means it's a v4 UUID (see https://www.uuidgenerator.net for more details)
