### ISSUE TITLE
multiple styles for one element

### ISSUE THREAD

**Issue by vinny1145** [BohemianCoding/developer.sketchapp.com#121]
i have found a problem when designing and that is that i want to be able to add multiple styles to one element to keep my design process as fast as possible but i have not found a way yet to do this.

maby just maby you guys can add this to sketch in the future.

have a great day peeps

**Comment by bomberstudios** [comment]
Hi there,

this is a repository to discuss development of Plugins and Extensions for Sketch. I'll forward your request to the relevant team.

Thanks! : )
