### ISSUE TITLE
source page looks a bit weird

### ISSUE THREAD

**Issue by robintindale** [BohemianCoding/developer.sketchapp.com#136]
http://developer.sketchapp.com/reference/api/source.html

![image](https://user-images.githubusercontent.com/2700528/34053193-b2239502-e1bd-11e7-906d-9fd57c3d5bf6.png)

**Comment by mathieudutour** [comment]
Hum weird. I'm redoing all the docs for the API so this will disappear anyway :)

**Comment by robintindale** [comment]
Looking at the source file 

https://github.com/BohemianCoding/developer.sketchapp.com/blob/gh-pages/reference/api/source.html

seems like merge markets were committed without resolving differences
