### ISSUE TITLE
Unclear: manifest.bundleVersion property

### ISSUE THREAD

**Issue by turbobabr** [BohemianCoding/developer.sketchapp.com#2]
> The version for the layout of the bundle an metadata. If excluded it is assumed the value is 1.

This property is just super weird. What is `layout` in this context? How this property works and affects Sketch?

**Comment by samdeane** [comment]
This is just a future-proofing mechanism for us. If, in the future, we saw a plugin with a bundleVersion > 1, we'd know that we could treat the other values in the metadata differently.

For now it's fine to omit it, or to set it to 1.

**Comment by turbobabr** [comment]
Thanks for the clarification. I got confused previously, because `bundleVersion` sounds like a version of a certain bundle instance I'm building. I think, It worth adding additional info that the property is for future use to avoid conflicts when manifest format is extended or gets some breaking changes.

I'd be happy to add such description myself, but as you can see my English isn't really good for the official documentation. :)

**Comment by samdeane** [comment]
Good plan - @bomberstudios?

**Comment by bomberstudios** [comment]
Indeed, let's get this updated : )
