### ISSUE TITLE
Is there a way to auto update or prompt user that theres an update for the plugin?

### ISSUE THREAD

**Issue by jamztang** [BohemianCoding/developer.sketchapp.com#22]
I was wondering if the Sketch's plugin manager will soon or already supports that just I've overlooked.

**Comment by matt-curtis** [comment]
AFAIK: no, I recall seeing/reading that Sketch doesn't do anything with the `version` identifier or `updateURL` for now.

Of course, you can write your own auto-updating mechanism using both those `.json` keys ;)

**Comment by bomberstudios** [comment]
There's nothing implemented yet, but the idea is that we'll use those keys when the time comes (soon, hopefully : )

But just for the sake of discussion, I'd love to hear your ideas about auto-updating (both from users' perspectives, and implementation-wise : )

**Comment by matt-curtis** [comment]
I don't think it would be a good idea to automatically update plugins, as too much could change between versions, and users could be caught off guard by functionality suddenly changing.

What seems like a good starting point, to me, is expanding the current Plugins preferences to indicate that there are updates available, and allow users to view changelogs, etc. Auto-updating should also be opt-in, developer-wise.

When Sketch detects that there are updated versions of a plugin available, it could indicate that there are pending plugin updates in the menu bar. 'Plugins' becomes 'Plugins (5)' maybe, or clicking 'Plugins' just shows an additional menu item, that says '5 updates available'. When clicked, it opens the Plugins preferences window, with 'Update Available' next to each plugin with an update available. The ability to show a changelog before they update (or not) would be great. Not sure how that would be implemented - maybe with a URL pointing to a `.md` file, or a new key in the existing plugin `manifest.json`?

Anyway, I'm just spitballing here...

**Comment by bomberstudios** [comment]
Yeah, we agree on the 'don't auto-update by default' bit. I've always found Safari's approach quite elegant (the "Automatically update…" option is off by default, IIRC):

![screenshot 2016-01-03 22 58 22](https://cloud.githubusercontent.com/assets/3832/12081009/4522d6ec-b26d-11e5-8dfd-aa391ebfa7cc.png)

Atom does something similar with bundles: you get a notification, but no auto updates (maybe there's a setting somewhere to enable it, I'm not a hardcode Atom user myself). They don't show release notes or changelogs, which surprises me a bit for a developer tool, but other than that their system seems to get out of your way (as a user) which is always a nice thing : )

Showing changelogs for Plugin updates could be nice, but *if* we did that they would be completely optional. TBH, I wouldn't count on there being a lot of those in the wild, but I love to be proven wrong when reality is better than assumptions!

**Comment by booc0mtaco** [comment]
So, these days, atom auto-updates packages, which might make it a less-than-ideal comparison :(

Here are a few other points for comparison:

- Patch-level updates might be appropriate for auto-updating
- Power users might have many plugins installed, so from an experience standpoint, it might be tricky to design a UI that allows for easy updates across plugins (or update all and cross fingers!)
- Updates will usually be accompanied with some feature changes, which may require illustration or explanation. There would likely be a need to allow for somewhat flexible descriptions (a la, sparkle) when prompted to update

I think another model for comparison could be the App Store.app update panel. It provides for some details here. Users would be able to update all , or by piecemeal selection, and shows one way to allow for "here's what's new". Perhaps Sketch could provide this info in a richer format (RSS-style)? That way, if the `<item>` doesn't contain a tag (e.g., `<description>`?), it would be skipped.

For a plugin I'm working on now, it has an embedded .app, which I was hoping could manage the whole update process. For example, the .app uses sparkle for app updates, and adds a bit of code to also update the plugin before sparkle kicks in. Were sketch to have updates, we could clean this up!

**Comment by bomberstudios** [comment]
> atom auto-updates packages

When did that happen? Mine is definitely _not_ doing it… is that a new preference?

**Comment by booc0mtaco** [comment]
Oh, so at some point I installed a package that auto updates packages. False-alarm! :( I should be more careful about where I get my dotfiles from.

**Comment by samdeane** [comment]
We definitely *do* want to do this. It's just a matter of juggling programmer time...

**Comment by booc0mtaco** [comment]
@samdeane definitely understood. The system we have in place works well now, updating the distributions thru sparkle (we require a desktop app for other tasks, so it keeps both in sync). Also backed by a github repo, so a proper push there lets raw files get pulled down pretty easily.

**Comment by mathieudutour** [comment]
Closing this as this is now possible: http://sketchplugins.com/d/229-updating-plugins
