### ISSUE TITLE
OpenStreetmap SVG and PDFs crash while loading

### ISSUE THREAD

**Issue by ir-tech** [BohemianCoding/developer.sketchapp.com#23]
While loading one of the attached files Sketch crashes.

I have Version 3.4.4 (17249) and am running on OSX 10.11.1 on a MacbookPro 11.4, Intel Core i7 with 16GB RAM

[vectorized.zip](https://github.com/BohemianCoding/developer.sketchapp.com/files/68402/vectorized.zip)

The crash log can be found here: http://pastebin.com/CsmRY98u

**Comment by bomberstudios** [comment]
Hi there,

please get in touch with support at mail@bohemiancoding.com, this repo is for the developer website only : )
