### ISSUE TITLE
Layout settings - columns calculation bug

### ISSUE THREAD

**Issue by alistairtweedie** [BohemianCoding/developer.sketchapp.com#28]
There seems to be a stray 1px when calculating the layout grid. Changing gutter to 20px changes to columns to 61px and vice versa.

![image](https://cloud.githubusercontent.com/assets/1608252/12169274/6722ce86-b52f-11e5-9905-f99b02574110.png)

**Comment by alistairtweedie** [comment]
I've worked out that the gutter is being halved to 10px and added to the outside on either side. Which is fine. However, for the grid system I've designed I'm required to have 20px on the outside on either side. I wonder if the option to choose the outside gutter size would be a reasonable feature request?

**Comment by bomberstudios** [comment]
Hi there,

please get in touch with support at mail@bohemiancoding.com, this repo is for the developer website only : )

**Comment by alistairtweedie** [comment]
Apologies, thanks! :)
