### ISSUE TITLE
Bug with big fonts

### ISSUE THREAD

**Issue by ramden** [BohemianCoding/developer.sketchapp.com#29]
This bug affects 3.4.4, issues with Sketch and Sketch Mirror

Here are some screenshots

1. Font Helvetica Neue - font size 24 upon selection:

![design](https://cloud.githubusercontent.com/assets/630532/12194662/f9f96248-b5f1-11e5-94ba-f6ae52c8e1fe.png)

2. Text editing - Helvetica Neue, font size 48

![design](https://cloud.githubusercontent.com/assets/630532/12194710/30a19838-b5f2-11e5-8756-1487a1e267e5.png)

The same result with other fonts, no difference.

On Sketch Mirror iOS app the fonts are the only "pain", they are sometimes broken in half or somehow transformed in display

**Comment by cjdowner** [comment]
Hi there, please get in touch with support at mail@bohemiancoding.com, as this repo is for the developer website only and not a place to file general issues. Thanks!
