### ISSUE TITLE
MSImageProxy no longer exists

### ISSUE THREAD

**Issue by chrisladd** [BohemianCoding/developer.sketchapp.com#32]
According to this class dump:
https://github.com/abynim/Sketch-Headers/tree/master/Headers

And this error message:
`2/9/16 11:59:35.229 AM Sketch[34925]: Exception: ReferenceError: Can't find variable: MSImageProxy
`

Although the docs believe it still walks among us:
http://developer.sketchapp.com/reference/MSImageProxy/

**Comment by chrisladd** [comment]
I've found I can use MSImageData instead:

```
var imageData = [[MSImageData alloc] initWithImage:image convertColorSpace:false];
var layer = [[MSBitmapLayer alloc] initWithFrame:frame image:imageData];
```

**Comment by matt-curtis** [comment]
Also ties into problem I mentioned in #30
