### ISSUE TITLE
Is saving to ".sketch" file is possible?

### ISSUE THREAD

**Issue by v-vodyanov** [BohemianCoding/developer.sketchapp.com#36]
I've read that with API developer can do pretty much the same as if it was just user actions, so I was wondering if I can save the whole document to ".sketch" file, but I haven't found anything about it. Is it really possible? If it is, I think it would be great to see some kind of code snippet in documentation about that.

**Comment by bomberstudios** [comment]
You can try:

```javascript
var doc = context.document
[NSApp sendAction:'saveDocument:' to:nil from:doc]
```

or

```javascript
var doc = context.document
[NSApp sendAction:'saveDocumentAs:' to:nil from:doc]
```

Hope it helps!
