### ISSUE TITLE
Text-shadow CSS & Edit -> Copy CSS Attributes

### ISSUE THREAD

**Issue by kimek** [BohemianCoding/developer.sketchapp.com#37]
As for me 'Edit -> Copy CSS Attributes' is only fetching one value for text shadow despite having 3 values of it (text-shadow) on one, same element.

Maybe Im doing something wrong... o.O?

btw. is there a purpose of using px on zero values ? ex. text-shadow: 0px 0px 0px 3px = text-shadow:0 0 0 3px ? (6 characters dropped )
w3 ref: "After a zero length, the unit identifier is optional."
w3 link: https://www.w3.org/TR/CSS2/syndata.html#length-units

**Comment by bomberstudios** [comment]
That looks like a bug on Sketch itself, so I'm closing this issue here : )

>  is there a purpose of using px on zero values

Makes our lives easier in the code that generates the CSS, but I'll see if we can improve that.
