### ISSUE TITLE
Can't get text style name

### ISSUE THREAD

**Issue by mobinni** [BohemianCoding/developer.sketchapp.com#38]
When you create a text style in sketch you can give it a name, however I cannot find how to get the name from the MSLayer:

```
layer.style().textStyle().????
```
I also looked in the header files and it looks like they're not linked?
![](http://i.imgur.com/Q99gpct.png)

**Comment by bomberstudios** [comment]
That's because text style don't reside at the layer level, but at the document level : )

Try this:

```
layer.documentData().layerTextStyles().sharedObjectForInstance(layer.style()).name()
```

Hope it helps!

**Comment by mobinni** [comment]
It did! Thanks so much for your help.
We should document this somewhere though? Right?

**Comment by bomberstudios** [comment]
> We should document this somewhere though? Right?

You're right. I'll try to add the docs for `MSDocumentData` : )
