### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by matt-curtis** [BohemianCoding/developer.sketchapp.com#4]
Since the site is hosted on GH pages, you write an AJAX search that trawls though the pages :) Or have it search an auto-generated database-like file...

just throwing ideas out there

**Comment by bomberstudios** [comment]
I have http://lunrjs.com on my radar, but other ideas are welcome : )

**Comment by CodingMammoth** [comment]
:+1:

**Comment by bomberstudios** [comment]
This seems to do what we need: https://github.com/slashdotdash/jekyll-lunr-js-search

**Comment by intemperie** [comment]
Noted. I think this can be integrated on the main site as well, so we use the same system for both. Let's have a chat whenever you have time :)

**Comment by bomberstudios** [comment]
Also: http://iamnotarealprogrammer.com/adding-site-search-with-lunr/ (I like this approach a bit better, since the `.json` file for lunr.js is generated on the fly)
