### ISSUE TITLE
Anyway to hook sketch saving event? Anyway to add menu item?

### ISSUE THREAD

**Issue by NickolasHu** [BohemianCoding/developer.sketchapp.com#40]
* 1 Is there any way to trigger sketch plugin event when sketch contents change. 
I check the class dump files and cannot find any solution.

* 2 Can I add menu item to the right click menu?

**Comment by bomberstudios** [comment]
> Is there any way to trigger sketch plugin event when sketch contents change. 

Not at the moment, but we're working on that : )

> Can I add menu item to the right click menu

That's currently not possible, but we'll think about it.
