### ISSUE TITLE
Unclear error Caught script exception: *** -[__NSArrayM objectAtIndex:]

### ISSUE THREAD

**Issue by NickolasHu** [BohemianCoding/developer.sketchapp.com#41]
Usually I come across the unclear error of sketch plugin compile log.  
[Which @Alejandro Martinez mention too.](http://alejandromp.com/blog/2015/8/10/color-theme-objective-c-sketch-plugin/). Is that means some kind of syntax error? Anyway can I get detail information about errors?

error log eg.
`Caught script exception: *** -[__NSArrayM objectAtIndex:]: index 3374 beyond bounds [0 .. 118]`

TIA.

**Comment by bomberstudios** [comment]
Hi there,

that's definitely an error in the logic of your code: you're probably iterating over a mutable array, and it's been modified while you loop over it.

The best place to ask questions about this is the [SketchPlugins mailing list](http://sketchplugins.com) : )
