### ISSUE TITLE
MSColor reference doesn't mention colorspaces

### ISSUE THREAD

**Issue by danielchasehooper** [BohemianCoding/developer.sketchapp.com#42]
The API reference for MSColor doesn't discuss colorspaces at all. This is very important if you want to get back the correct color! 

After class dumping Sketch's headers and trying a few things, it seems like MSColor's rgb values are in the sRGB color space. Though even after looking at the class-dump headers it's unclear if MSColor will use that space all the time, or if that could change color-to-color or without warning in future sketch updates. The Api reference should address these concerns and give guarantees about what assumptions about color space are safe to make.

**Comment by pieteromvlee** [comment]
That is correct. MSColor is deliberately color-spac agnostic. When rendering to the screen we use create an NSColor using the current screen's color profile. When exporting, we use the sRGB color space
