### ISSUE TITLE
Is there anyway to embed a video inside of a sketch file?

### ISSUE THREAD

**Issue by bernatfortet** [BohemianCoding/developer.sketchapp.com#45]

**Comment by bomberstudios** [comment]
I don't think that's possible without insane amounts of hacking : )

Why would you want to do that?

**Comment by shinwang1** [comment]
I would embed on-boarding video as a feature to my prototype.

**Comment by samdeane** [comment]
The Sketch file format is a zip file, so in theory you might be able to unzip it, insert extra files into it, and zip it up again. Sketch wouldn’t know anything about them though, so as soon as it saved the file, the extra content would be lost.

Allowing plugins to include extra content files in the archive is something we’ve discussed, but there are a few potential problems with it.
