### ISSUE TITLE
SVG Creating and Exporting Errors

### ISSUE THREAD

**Issue by arielview** [BohemianCoding/developer.sketchapp.com#46]
**Creating SVGs**
- When creating SVGs in Sketch and then uploading them to Android Studio they appear pixelated and the color doesn't render correctly.
<img width="360" alt="graphicactivityonboardingexportedtoandroidstudio_720" src="https://cloud.githubusercontent.com/assets/1046046/15158919/e22ed07e-16a6-11e6-8639-d0af9a3080ec.png">

![graphicdataonboarding](https://cloud.githubusercontent.com/assets/1046046/15159028/594cca80-16a7-11e6-9fec-deb3e453e52b.png) - png attached instead of svg becuase svg files not accepted.

**Exporting SVGs**
- When creating svg in Illustrator and then exporting them into Android studio from Sketch the svg usually looks correct, but Android Studio says there are scaling errors.

**Comment by bomberstudios** [comment]
Hi there,

this is a repository to discuss development of Plugins and Extensions for Sketch. If you need support for Sketch itself, please get in touch with us at https://sketchapp.com/support/contact/

Thanks! : )
