### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by kimek** [BohemianCoding/developer.sketchapp.com#47]
Hi Guys
Your software is great and we love it with my designer.
Is there a chance to add REM units to fonts. 

This will be awesome feature !

**Comment by bomberstudios** [comment]
Hi there,

this is a repository to discuss development of Plugins and Extensions for Sketch. If you need support for Sketch itself, please get in touch with us at https://sketchapp.com/support/contact/

Thanks! : )
