### ISSUE TITLE
Dockable panels (like Craft)

### ISSUE THREAD

**Issue by evgenytr** [BohemianCoding/developer.sketchapp.com#50]
Is there documentation on how to create a dummy dockable panel? As Craft demonstrates it's possible, but there are no cues anywhere

**Comment by bomberstudios** [comment]
Well, what Craft is doing is basically a hack (i.e: they attach their UI to our split view) and while it gets the job done I don't think we should be encouraging such hacks by documenting how they're done : )

That being said, we're aware of this need and will try to add an official way for Plugins to create panels inside Sketch!
