### ISSUE TITLE
AddNewStylePart undefined.

### ISSUE THREAD

**Issue by fuggfuggfugg** [BohemianCoding/developer.sketchapp.com#51]
Appreciate any assistance. My current version is 3.8.1 (29687)

![screen shot 2016-05-19 at 9 20 49 pm](https://cloud.githubusercontent.com/assets/5616123/15414337/aec21968-1e07-11e6-9a61-acb1cd31863d.png)

**Comment by fuggfuggfugg** [comment]
A class dump on MSStyle.h between 3.7 vs 3.8 shows fillsGeneric changed from <MSFillStyleCollection> to <MSArray>. This seems to break addNewStylePart method.

![screen shot 2016-05-19 at 10 10 39 pm](https://cloud.githubusercontent.com/assets/5616123/15415127/a8c2c8f8-1e0e-11e6-93e3-253fd36a89bc.png)

**Comment by fuggfuggfugg** [comment]
Finally after much trial and error, Got it to work. There's no documentation 👎     

    var blackColor = MSColor.colorWithNSColor(NSColor.colorWithGray(0.5))
   
    var fill = MSStyleFill.alloc().init()

    fill.fillType = 0

    fill.colorGeneric = blackColor

    container.style().fills().addObject(fill)

**Comment by bomberstudios** [comment]
Sorry about that, I shared that info in the mailing list but never got around to update the site: http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2016-May/003781.html

Will do that now : )
