### ISSUE TITLE
"updateURL" is undocumented for sketch

### ISSUE THREAD

**Issue by booc0mtaco** [BohemianCoding/developer.sketchapp.com#55]
Hey there,

I was wondering if you could provide some documentation for how *.json files are handled for app updates. Is it somehow similar to what Sparkle does for native apps?

was referring to the reference here : <http://developer.sketchapp.com/introduction/plugin-bundles/> 

Is this functionality working in the most recent version of sketch, and how might a plugin author (me!) use it.

**Comment by samdeane** [comment]
The updateURL entry in the manifest isn’t actually used by Sketch at the moment, so you could think of it as just being documentation right now.

In the future though we’d like to be able to offer the user an update button for installed plugins within Sketch, so we’d encourage plugin authors to fill it in with a valid URL. 

Actually I think that example is a bit misleading, as I think the URL should point to a zip archive for the plugin, and not a json file. What do you think @bomberstudios?

**Comment by booc0mtaco** [comment]
Speaking from prior experiences, a JSON file might offer some more flexibility (like linking to changelog information, previous versions, public keys for security purposes, etc.) E.g., semver in the JSON would allow users to upgrade to patched 1.x.y versions but not go to 2.x.y if they preferred.

Either way, thanks for the update. Wanted to be sure I wasn't missing something.

**Comment by samdeane** [comment]
Yeah, I guess it essentially needs to point at some sort of appcast style resource (a la Sparkle) with metadata about the update, so you are correct (that’s probably why the example is the way it is). 

For the sake of consistency I might be tempted to actually use the same appcast format as Sparkle (though probably not use Sparkle to manage these downloads).

For the sake of simplicity on the other hand, a .json format of our own devising might be better.

**Comment by bomberstudios** [comment]
Will add a note about it being currently unused to the docs, thanks for pointing this out @booc0mtaco : )
