### ISSUE TITLE
Creating MSSliceLayer with the same frame as selected layer

### ISSUE THREAD

**Issue by RGSSoftware** [BohemianCoding/developer.sketchapp.com#60]
I’ve reviewed .sketch docs and tried many different solutions, but I couldn’t add a MSSliceLayer with the same frame as the selected layer. When I added MSSliceLayer to the current document it’s center point is the current document center point and not the selected layer.

Maybe, I’m missing something simple.

Example:
https://github.com/RGSSoftware/sketchScriptFail

**Comment by bomberstudios** [comment]
Try this:

```
MSSliceLayer.sliceLayerFromLayer(layer)
```

Hope it helps!

**Comment by RGSSoftware** [comment]
It works, thanks. 

If possible can the docs http://developer.sketchapp.com/reference/class/MSSliceLayer/ reflect the headers https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSSliceLayer.h in the future.
