### ISSUE TITLE
backgroundColorGeneric readonly?

### ISSUE THREAD

**Issue by JoeManto** [BohemianCoding/developer.sketchapp.com#61]
**Notice**: This issue isn't that major i just think it should be addressed. I could just be dumb and totally missed something in the reference.

I've been trying to use  

> artboard.backgroundColorGeneric = MSColor.colorWithNSColor(NSColor.colorWithGray(0.0))

referenced on [reference](http://developer.sketchapp.com/reference/class/MSArtboardGroup/) **- Sketch's Developer website.**

**Finally after trial and error i found that its**

> artboard.backgroundColor = MSColor.colorWithNSColor(NSColor.colorWithGray(0.0))

**Comment by bomberstudios** [comment]
Ah, you're right. Will fix : )
