### ISSUE TITLE
Request:  Example of development workflow

### ISSUE THREAD

**Issue by mrbinky3000** [BohemianCoding/developer.sketchapp.com#72]
Can you add an example of the workflow involved with creating and editing a sketch plugin.  Do I have to restart Sketch every time I edit the source of a plugin?  Or is there a way to force sketch to reload the plugin automatically?  Is there a command line for forcing sketch to reload plugins?  Something I could add to a GULP script's "watch" routine?

**Comment by samdeane** [comment]
There are [a few `defaults` settings which will help](http://developer.sketchapp.com/introduction/preferences/). 

As long as you're not working on long-running plugins, setting `defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES` is enough to get Sketch to reload the plugin each time it's run.

**Comment by samdeane** [comment]
You are right though, we should do a walkthrough at some point of how to set up your development environment.

**Comment by LeonardPauli** [comment]
Helpful script for viewing the plugin logs without noise in terminal: Just start the script and let it roll :) [view plugin log script on GitHub](https://github.com/LeonardPauli/LayerRenamer/blob/master/view%20plugin%20log)
