### ISSUE TITLE
Colorpicker instance

### ISSUE THREAD

**Issue by Quball** [BohemianCoding/developer.sketchapp.com#77]
I have been looking around to find any info on if it's possible to get the Sketch colorpicker instance for a plugin I am planning. But it doesn't look like it's available. Apart from the native colorpicker which isn't really useful in my case.

Is there a way to get the Sketch colorpicker or any plans to open it up to the plugin api?

**Comment by bomberstudios** [comment]
Take a look at https://github.com/heysketch/sketch-color-picker-plus : )
