### ISSUE TITLE
centerOnLayer function removed?

### ISSUE THREAD

**Issue by blitzcrank** [BohemianCoding/developer.sketchapp.com#85]
The documentation shows a 'centerOnLayer' function being available on NSDocument but can't make it work. Any ideas?

http://developer.sketchapp.com/reference/api/class/api/Document.js~Document.html#instance-method-centerOnLayer

```
var doc = context.document
doc.centerOnLayer()
```

returns: TypeError: doc.centerOnLayer is not a function. (In 'doc.centerOnLayer()', 'doc.centerOnLayer' is undefined)

**Comment by bomberstudios** [comment]
You need to access the actual JS API to use its methods, like this:

```js
var api = context.api()
var doc = api.selectedDocument
var selection = doc.selectedLayers
selection.iterate(function(layer){
    doc.centerOnLayer(layer)
})
```

Hope it helps!
