### ISSUE TITLE
Bug Report: The document "[_File-Name_].sketch" could not be opened. Unarchiving failed.

### ISSUE THREAD

**Issue by JonHendershot** [BohemianCoding/developer.sketchapp.com#86]
This has happened to me more than a couple times. The app crashes and corrupts the file. The file is taken from its original size and is dropped to 25kb and unsalvageable. No idea what causes it. No idea how to fix it. Have been burned by this issue a couple times.

**Comment by bomberstudios** [comment]
Hi there,

this is a repository to discuss development of Plugins and Extensions for Sketch. If you need support for Sketch itself, please get in touch with us at https://sketchapp.com/support/contact/

Thanks! : )
