### ISSUE TITLE
Copy & Pasting symbol create new object in symbol page.

### ISSUE THREAD

**Issue by darshan06** [BohemianCoding/developer.sketchapp.com#90]
Hi,

I have Latest sketch version 43.2 and I am very tired with one issue of symbol duplicates.
Whenever I copy and past any symbol sketch creates its duplicate object in the symbol panel and same thing not happen whenever I do Alt+drag command.

Please do changes and make it as it was before as my habit is to copy & paste symbol rather than time consuming Insert-> symbol -> pick anything...
Let me know for further clarification on this.

Thanks!

**Comment by bomberstudios** [comment]
Hi there,

this is a repository to discuss development of Plugins and Extensions for Sketch. If you need support for Sketch itself, please get in touch with us at https://sketchapp.com/support/contact/

Thanks! : )
