### ISSUE TITLE
Setting Text Font

### ISSUE THREAD

**Issue by Nealo** [BohemianCoding/developer.sketchapp.com#92]
Hey, I'm trying to set some Text's font property, but it seems to require the font name to be a NSFont value and not a NSString.

I tried using `[NSFont fontWithName:'Gotham']` and `NSFont.fontWithName('Gotham')` but it comes back saying:

`TypeError: NSFont.fontWithName_ is not a function. (In 'NSFont.fontWithName_( 'Gotham HTF')', 'NSFont.fontWithName_' is undefined)
line: 45`

Here is the code I'm using to create the text:

`group.newText({alignment: NSTextAlignmentLeft, systemFontSize: 50, text:copy, font: [NSFont fontWithName:'Gotham HTF'] })`

It works fine if I don't set the font. 

Is there a way to set the font with creating a NSFont object? If not, how can I initialize the NSFont object since the standard fontWithName method isn't working.

**Comment by samdeane** [comment]
I think you need `NSFont.fontWithName_size_("Gotham", 12)`.

**Comment by samdeane** [comment]
(an `NSFont` is actually a font/size combination)

**Comment by Nealo** [comment]
You sir are a champion—it worked perfectly. Thanks a lot. I'm mostly a JS-dev so I'm trying my best to decipher everything.
