### ISSUE TITLE
Crash when calling MSExportRequest configureForLayer

### ISSUE THREAD

**Issue by emilienh** [BohemianCoding/developer.sketchapp.com#95]
The following code used to work for exporting an entire page to an image.

```
var doc = context.document;
var pages = [doc pages];
var page = [pages objectAtIndex:0];

var frame = [page contentBounds];
var request = MSExportRequest.new();
request.configureForLayer([page currentRoot]);  // Crash
request.rect = frame;
request.includeArtboardBackground = true;
[doc saveArtboardOrSlice:request toFile:"/tmp/sketch.png"];
```

Since Sketch v43 it's been crashing the app with the following error:
```
[MSPage layer]: unrecognized selector sent to instance
```

There isn't a replacement for this in the new API as far as I know.

**Comment by samdeane** [comment]
Actually, there is support for exporting in the API.

You can find an example plugin [here](https://github.com/BohemianCoding/plugins.examples.exporting/blob/develop/Exporting%20Examples.sketchplugin/Contents/Sketch/exporting.js).

It should be linked in to the `developer.sketchapp.com` website, but for some reason it isn't :(

**Comment by emilienh** [comment]
Thanks, this is great!
